name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 170.64.238.91 # Your Droplet's IP
          username: leelawebdev
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/leelaweb-client
            git pull origin main
            npm install
            npm run build
            pm2 restart leelaweb-client
